server:
  port: 8500
  servlet:
    context-path: /

openai-service:
  api-key: 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
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 20000
    connect-timeout: 20000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions

logging:
  level:
    com.github.javapuzzle.service.openaiclient: TRACE

# Spring
spring:
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health:
    circuitbreakers:
      enabled: true
